version: '3.8'

services:
  postgres:
    image: postgres
    container_name: pg-shortlinks
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=shortlinks
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis-shortlinks
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

volumes:
  postgres:
  redis:

